"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import logging
import sys
from pathlib import Path

import structlog

from config.appconfig import settings as env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# True when running under pytest or `manage.py test`.
_TESTING = "pytest" in sys.modules or "test" in sys.argv


# All environment-driven config comes from the typed AppSettings model.
# See config/appconfig.py.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.django_secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.django_debug

ALLOWED_HOSTS = env.allowed_hosts_list


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "chat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise serves static files directly (so DEBUG=False works in a container).
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.postgres_db,
        "USER": env.postgres_user,
        "PASSWORD": env.postgres_password,
        "HOST": env.postgres_host,
        "PORT": str(env.postgres_port),
        # Django 5.1+ built-in psycopg3 connection pool. Disabled under tests:
        # pooled connections stay open and block dropping the test database.
        "OPTIONS": {} if _TESTING else {"pool": {"min_size": 1, "max_size": 10}},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- Auth / email -----------------------------------------------------------

# Session login is used by the JSON auth endpoints under /api/auth/.
LOGIN_URL = "/api/auth/login/"

EMAIL_BACKEND = env.email_backend
EMAIL_HOST = env.email_host
EMAIL_PORT = env.email_port
EMAIL_HOST_USER = env.email_host_user
EMAIL_HOST_PASSWORD = env.email_host_password
EMAIL_USE_TLS = env.email_use_tls
DEFAULT_FROM_EMAIL = env.default_from_email

# Frontend route that receives ?uid=&token= from the reset email.
PASSWORD_RESET_FRONTEND_URL = env.password_reset_frontend_url


# --- LangGraph agent configuration -----------------------------------------

# Ollama connection + model used by the agent.
OLLAMA_BASE_URL = env.ollama_base_url
OLLAMA_MODEL = env.ollama_model
OLLAMA_EMBED_MODEL = env.ollama_embed_model
OLLAMA_TIMEOUT = env.ollama_timeout

# Connection string the LangGraph Postgres checkpointer uses to persist state.
CHECKPOINTER_DSN = env.database_dsn

# RAG: pgvector store settings. langchain-postgres wants a SQLAlchemy-style URL.
RAG_COLLECTION = env.rag_collection
RAG_TOP_K = env.rag_top_k
VECTOR_DSN = env.database_dsn.replace("postgresql://", "postgresql+psycopg://", 1)


# --- Observability ----------------------------------------------------------

# structlog: pretty console logs in DEBUG, JSON lines otherwise.
_shared_processors: list = [
    structlog.contextvars.merge_contextvars,
    structlog.processors.add_log_level,
    structlog.processors.TimeStamper(fmt="iso"),
]
structlog.configure(
    processors=[
        *_shared_processors,
        structlog.dev.ConsoleRenderer() if DEBUG else structlog.processors.JSONRenderer(),
    ],
    wrapper_class=structlog.make_filtering_bound_logger(logging.INFO),
    logger_factory=structlog.PrintLoggerFactory(),
    cache_logger_on_first_use=True,
)

# Sentry is enabled only when a DSN is provided (django integration is
# auto-detected by sentry-sdk[django]).
if env.sentry_dsn:
    import sentry_sdk

    sentry_sdk.init(
        dsn=env.sentry_dsn,
        traces_sample_rate=env.sentry_traces_sample_rate,
        send_default_pii=False,
    )
